### ISSUE TITLE
Realted to size

### ISSUE THREAD

**Issue by kandoi1994** [rgiduthuri/openvx_tutorial#15] opened 2018-03-26 10:41 UTC
Hello ,
In your sample example if I change the video size then image is overlapping . can you explain why this is working with only one size I:e (768x576) , if I reduce any size then output not came properly . 

Thanks and Regards 
Subham

**Comment by rgiduthuri** [comment] 2018-03-26 14:50
Interesting...

Can you please attach the image with overlapping that you’re seeing?

**Comment by kandoi1994** [comment] 2018-03-27 04:19
output 1 (overlapping ) :-  ![sample1](https://user-images.githubusercontent.com/26054552/37946566-9fe7edb8-3175-11e8-92b1-691b47e3c993.png)  

output 2 (no overlapping ) :-  ![sample2](https://user-images.githubusercontent.com/26054552/37946567-a039b346-3175-11e8-9a4a-2a0edfc3258b.png)

output 3  ( different behavior ) :- ![sample3](https://user-images.githubusercontent.com/26054552/37946568-a087adda-3175-11e8-9fa7-849a9bf3df6e.png)

Different size different output 

 comment

**Comment by rgiduthuri** [comment] 2018-03-27 06:17
Are you displaying input images? If so, the problem could be with OpenCV library. Check the dimensions of image being read using OpenCV call.

**Comment by kandoi1994** [comment] 2018-03-27 06:20
I Displaying both I/p and o/p in your sample example of tensor object but I only change the video and size of video.

**Comment by rgiduthuri** [comment] 2018-03-27 06:32
I think the problem is with dimensions that you’re passing and dimension of image doesn’t match. Give an image with same dimensions as dimensions you’re hardcoinf in your program.

**Comment by kandoi1994** [comment] 2018-03-27 07:02
I not write any program I used your sample example ( tensor objects ) . https://github.com/rgiduthuri/openvx_tutorial/blob/master/tutorial_exercises/solution_exercise3/solution_exercise3.cpp

I am not able to find any dimension is hardcoinf  by you in your program . can you help me in which line number dimension is mentioned.

**Comment by rgiduthuri** [comment] 2018-03-27 07:15
I suggest you single step through the code in debugger. This way you’ll understand the code well.

**Comment by kandoi1994** [comment] 2018-03-27 10:37
I saw your YouTube video where you explain the tensor object example . you not say dimension any where and not used . please help .

**Comment by rgiduthuri** [comment] 2018-03-27 13:52
It will be hard for me to explain every bit. You need to read the OpenVX spec, C header files, and tutorial code to figure these things out. In order to be able to use OpenVX we expect that users are proficient in C/C++ language. 

I’m closing this issue as there is no bug in the tutorial exercise code.

**Closed as completed by rgiduthuri** 2018-03-27 13:52 UTC
